config/routes.rb
Rails.application.routes.draw do
  get 'items/index'
  root 'notes#index'

  resources :notes do
    resources :item
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < Notebook
  belongs_to :note, class_name: "Note"
  has_many :tagged_items
  has_many :item_taggings , through: :tagged_items
end

app/models/item_tagging.rb
class ItemTagging < ApplicationRecord
    has_many :tagged_items
    has_many :items , through: :tagged_items, class_name: 'Note'
    
end

app/models/note.rb
class Note < Notebook
  has_many :items, class_name: "Item", foreign_key: "note_id"

  validates :title, presence: true
  validates :description, presence: true
end

app/models/notebook.rb
class Notebook < ApplicationRecord
    # has_many :items , class_name: "Notebook"
    
    # belongs_to :notes, class_name: "Notebook"
    # scope :notes, -> { where(type: 'Note') }
    # scope :items, -> { where(type: 'Item') }
end

app/models/tagged_item.rb
class TaggedItem < ApplicationRecord
  belongs_to :item, class_name: "Note"
  belongs_to :item_tagging
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end
  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @note = Note.find(params[:note_id])
    @item = @note.items.create(item_params)
    redirect_to note_path(@note)
    byebug
  end

  private
    def comment_params
      params.require(:item).permit(:title, :description)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all
  end

  def show
    @note = Note.find(params[:id])
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    if @note.save
      redirect_to notes_path
    else
      render :new
    end  
  end

  private
    def note_params
      params.require(:note).permit(:title, :description)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/items/index.html.erb
<h1>Items</h1>

<ul>
  <% @items.each do |item| %>
    <li>
      <%= link_to item.title, item %>
    </li>
  <% end %>
</ul>

<%= link_to "New Item", new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= form_for @item do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/show.html.erb
<h1><%= @item.title %></h1>

<p><%= @item.description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/index.html.erb
<h1>Notes</h1>

<ul>
  <% @notes.each do |note| %>
    <li>
      <%= link_to note.title, note %>
    </li>
  <% end %>
</ul>

<%= link_to "New Note", new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= form_with model: @note do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/show.html.erb
<h1><%= @note.title %></h1>

<p><%= @note.description %></p>

<h2>Item</h2>

<%= form_for @item do |form| %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>